[package]
edition = "2021"
name = "daat-locus-md"
version = "0.3.6"
description = "Fork of ratatui-markdown v0.3.6 with ratatui 0.30 support"
license = "MIT OR Apache-2.0"
repository = "https://github.com/shadow3aaa/ratatui-markdown"

[features]
default = []
markdown = []

[dependencies]
pulldown-cmark = "0.13"
ratatui = "0.30"
unicode-width = "0.2"

[lib]
name = "daat_locus_md"
path = "src/lib.rs"
doctest = false
